### PR TITLE
Fixed undefined variable

### PR DESCRIPTION
**Pull request by diegotremper**

### CODE REVIEW

**Comment by alexanderby** [comment]
Please merge. The code breaks in strict mode.

**Comment by ariutta** [comment]
Thanks!

**Comment by ariutta** [comment]
If you're interested, I'm happy to transfer this repo to you. Just let me know.

**Comment by diegotremper** [comment]
Please,  do it. 
Thanks!

**Comment by ariutta** [comment]
OK, just make sure to keep credit to the original author Stoyan Stefanov: http://www.phpied.com/rgb-color-parser-in-javascript/

**Comment by ariutta** [comment]
I tried transferring, but I got an error message saying "repo diegotremper/rgb-color already exists". Maybe you need to delete your fork so I can transfer? Anyway, I added you as a collaborator to this repo.

**Comment by diegotremper** [comment]
Ok, I've deleted repo now. Please try again.

**Comment by ariutta** [comment]
Done. I think once you accept the request, it's all yours.

**Pull request merged**
